export const SET_LOCATION_FILTER = 'app/SET_LOCATION_FILTER';

export const GET_LOCATIONS = 'app/GET_LOCATIONS';
export const GET_LOCATIONS_SUCCESS = 'app/GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_ERROR = 'app/GET_LOCATIONS_ERROR';